### ISSUE TITLE
新建文件夹报错

### ISSUE THREAD

**Issue by czhoucc** [ilime/Petal#10]
我用的是ubuntu 16.04，我之前把home里面的Music文件夹删掉了，所以第一次打开的时候
`mkdir ~/Music/PETAL豆瓣FM`
会报错。改成
`mkdir -p ~/Music/PETAL豆瓣FM`
就好了。

另外如果文件夹名是不是不要用中文比较好。

**Comment by g1eny0ung** [comment]
感谢反馈，之后我会判断一下Music文件夹 📁  是否存在再创建的。

另外文件夹用中文应该没什么大问题的。

**Comment by czhoucc** [comment]
另外，是否可以让Petal记住上次关闭时的窗口位置？
现在好像默认启动时都是在屏幕正中央，我在用双屏，所以每次它都在两个屏幕的中间。
或者可以判断哪个是主屏幕，然后显示在主屏幕的中央，而不是所有屏幕的正中央。

非常感谢开发Petal！

**Comment by g1eny0ung** [comment]
Thx👌 我回头尝试一下，这个issue先不要关，做完了会反馈在这里。

**Comment by czhoucc** [comment]
另外2，是否可以记住最后播放的频道。
现在每次启动都是播放豆瓣精选MHz，需要手动选到我的私人MHz。
谢谢！

**Comment by g1eny0ung** [comment]
@czhoucc [Version 2.12](https://github.com/ilime/Petal/releases/tag/v2.12.0)

最后一个记住最后播放频道没有做，最近有点忙，有空我再实现哈哈。

你测试一下有没有问题的。

我会新开一个 issue 去 track 记住最后播放频道的进度。

**Comment by czhoucc** [comment]
@g1eny0ung 测试过了，没问题！
非常感谢！

**Comment by g1eny0ung** [comment]
@czhoucc Hello，记住最后播放频道的东西拖了很久真是不好意思，今天我看了一下之前写的代码，写的有点死，如果做这个的话难度有点大。。原因是这样的：

因为之前写的代码里面，获取频道等许多API都写成了异步，如果只改这些也没什么，但是有一些额外地操作，比如修改 Mac TouchBar 的状态，记录当前的播放状态（因为有很多播放模式，没有同步可能会造成冲突），更新到文本数据库等等，修改这些比较繁琐，为了不影响之前已有的功能，造成更大规模的修改，这个功能我准备放弃了，先保持现状。

[issue#12](#12) 将会被关闭，最后感谢你的使用。～ ❤️
