### ISSUE TITLE
The default behavior of close button

### ISSUE THREAD

**Issue by richardkwo** [ilime/Petal#13]
Running petal on macOS. The current behavior of the "close" button (x) is to quit. Personally, I think it would be a better idea to "hide" when that button is clicked. Meanwhile, ⌘ + Q could be reserved to "quit".

**Comment by g1eny0ung** [comment]
I think so. Will be setting in next release! 👍

**Comment by richardkwo** [comment]
Excellent! Thanks for the great work.

**Comment by g1eny0ung** [comment]
[FInish in version 2.14.0](https://github.com/ilime/Petal/releases/tag/v2.14.0)
