### ISSUE TITLE
Can't update settings

### ISSUE THREAD

**Issue by junjiah** [ilime/Petal#14]
On latest release v2.16.0, on macOS Mojave 10.14.3

In settings page（设置）, clicking items under「其他配置」doesn't toggle the checkbox. Saving（保存）works fine. Developer console doesn't show any warning or error.

![image](https://user-images.githubusercontent.com/2631380/54050597-74ad7200-4194-11e9-84df-a1452a391e55.png)

**Comment by g1eny0ung** [comment]
I test it. Really can't toggle the checkbox. I will solve this problem tomorrow.

**Comment by g1eny0ung** [comment]
@junjiah Already fixed. I don't release a new version. Redownload version 2.16.0 and try it, will works. 😆

**Comment by junjiah** [comment]
confirmed it's fixed
