### ISSUE TITLE
可以设置默认启动是私人mhz吗？  每次启动默认是豆瓣精选，还要手动调一下～～

### ISSUE THREAD

**Issue by mvdfish** [ilime/Petal#22]
可以设置默认启动是私人mhz吗？  每次启动默认是豆瓣精选，还要手动调一下～～

**Comment by g1eny0ung** [comment]
之前有人提过这个功能，参考 [https://github.com/ilime/Petal/issues/10#issuecomment-486522122](https://github.com/ilime/Petal/issues/10#issuecomment-486522122)。

既然都很强调这个功能那我有时间做一下吧 🤣 ，有点麻烦，需要重构一下代码。

**Comment by mvdfish** [comment]
感谢～～～辛苦

**Comment by g1eny0ung** [comment]
在版本 2.18.0 中已完成。https://github.com/ilime/Petal/releases/tag/v2.18.0
