### ISSUE TITLE
OSX 菜单栏歌词

### ISSUE THREAD

**Issue by lxs137** [ilime/Petal#26]
如题。我稍微调研了一下，用多个Tray应该不行，考虑可行的方案是Tray里放一个nativeImage（按钮歌词绘制在一张图片上），自己根据点击位置来处理。 

有意接手这个任务

**Comment by g1eny0ung** [comment]
没问题，如果用一个nativeimage来代替的话，需要将icon拼接起来，我可以帮你做图标的拼接。至于歌词显示，我觉得可以放在再下一个版本做，因为歌词滚动的代码其实写的不算太好，我想改一下。

还有就是只能Mac做这个功能，win和linux还是得保留之前的菜单栏，因为这两个平台应该不支持。

我们可以在 gitter 上聊，我 gitter 全天都在。https://gitter.im/ilime/Petal

**Comment by g1eny0ung** [comment]
@lxs137 Hello，在 [2.19版本](https://github.com/ilime/Petal/releases/tag/v2.19.0) 我已经完成了新的菜单栏图标，但是暂时不会加入歌词显示，你可以先试用一下。😆

**Comment by lxs137** [comment]
good. 提个小建议，菜单栏的图标用黑白的会好一点，我菜单栏里的这些应用，只有这个是彩色的😆

**Comment by g1eny0ung** [comment]
哈哈，我是想着跟 Touch Bar 保持一致，就都是彩色的了。但是我觉得彩色的也很不错，有一些辨识度。

**Comment by Democookie** [comment]
> 哈哈，我是想着跟 Touch Bar 保持一致，就都是彩色的了。但是我觉得彩色的也很不错，有一些辨识度。

感觉菜单栏图标太突出啦，😂和Mac的整体格调都不太一样，还有Petal图标也有点丑😢。

**Comment by g1eny0ung** [comment]
@Democookie emmm，我想说的是每个人心中的“好看”是不一样的，所有的Icons和Logo都是我学习sketch设计的，我并不是专业的UI Design，只是凭感觉设计了一下。如果你觉得不太好看，欢迎你为Petal设计一套。

**Comment by g1eny0ung** [comment]
@lxs137 @Democookie #28
