### ISSUE TITLE
关于 Petal 的 UI

### ISSUE THREAD

**Issue by Democookie** [ilime/Petal#27]
@Democookie emmm，我想说的是每个人心中的“好看”是不一样的，所有的Icons和Logo都是我学习sketch设计的，我并不是专业的UI Designer，只是凭感觉设计了一下。如果你觉得不太好看，欢迎你为Petal设计一套。

_Originally posted by @g1eny0ung in https://github.com/ilime/Petal/issues/26#issuecomment-511171958_

**Comment by Democookie** [comment]
还还有就是现在的界面不够简洁，优美「按钮太多啦」。可以多参考同类的Mac播客和音乐类应用，比如网页云音乐Mac菜单栏的设计～，如果需要UI方面的支持我可以提供呀

**Comment by g1eny0ung** [comment]
我觉得你可以用实际的作品来为这个应用做贡献，如果你只是用语言来描述在设计方面哪里不行的话，我并没有很大精力来根据你的需求去做一些改动，这是一个开源的应用，希望你也能用实际的行动来表示你的想法。

**Comment by Democookie** [comment]
> 我觉得你可以用实际的作品来为这个应用做贡献，如果你只是用语言来描述在设计方面哪里不行的话，我并没有很大精力来根据你的需求去做一些改动，这是一个开源的应用，希望你也能用实际的行动来表示你的想法。

我已经说了我可以提供UI方面的帮助呀，如果你觉得是我个人的需求那不要理会好啦，只是说一些我的看法，UI方面的确很多见仁见智。「我还没有实际参与过开源项目的设计工作哈，所以什么样的沟通交通方式也没经验」，可能我一上来就说图标有点丑多少让人有点不感冒吧😂。
