### ISSUE TITLE
请问可以设置全局快捷键吗？

### ISSUE THREAD

**Issue by superchong-zc** [ilime/Petal#29]
Happy using Petal :hibiscus: ~.

If you want to open an issue:

Please make sure:

* [ ] Tell about your system info. (你的系统信息)
* [ ] The steps of your action. (你的操作步骤)
* [ ] In order to solve this issue better, It's best to have your error message or a screenshot. (为了更好的解决这个问题，最好能够提供一下你的错误信息或者是一张截图)

**Comment by g1eny0ung** [comment]
目前还不可以。

**Comment by leohxj** [comment]
@g1eny0ung 
menu 上的快捷操作可以添加一个红星按钮么？

**Comment by g1eny0ung** [comment]
@leohxj 可以的，后面1到2个版本之间会加上，最近有些忙，还请见谅哈。

**Comment by SammyStewart** [comment]
状态栏能加个暂停按钮吗？
<img width="126" alt="屏幕快照 2019-07-27 10 15 51" src="https://user-images.githubusercontent.com/52340561/61988751-50293800-b058-11e9-88ed-56a35eb4aeea.png">

**Comment by g1eny0ung** [comment]
@SammyStewart 可以的

**Comment by g1eny0ung** [comment]
除全局快捷键外，其他提到的功能已完成，下个版本就可以使用了。关闭issue。

**Comment by leohxj** [comment]
thanks
