### ISSUE TITLE
windows10无法运行

### ISSUE THREAD

**Issue by pcwuyu** [ilime/Petal#36]
![TIM截图20190727145434](https://user-images.githubusercontent.com/6291329/61991135-69dd7600-b07e-11e9-861b-7de81decf5ca.png)
![Snipaste_2019-07-27_14-55-55](https://user-images.githubusercontent.com/6291329/61991145-7e217300-b07e-11e9-8be5-4f5e438cdc63.jpg)

**Comment by g1eny0ung** [comment]
直接就打不开嘛，还是用着用着自己关闭了呢？

我昨天也在我的 windows 笔记本上用了，我这边没有发现这种情况。

**Comment by pcwuyu** [comment]
是直接就打不开

Yue Yang <notifications@github.com> 于2019年7月29日周一 上午9:07写道：

**Comment by g1eny0ung** [comment]
我这边还无法复现这个问题，所以暂时可能解决不了

**Comment by g1eny0ung** [comment]
Since there is no response for a long time, close the issue.
