### ISSUE TITLE
mac osx 经常出现窗口丢失（某次最小化之后就无法打开窗口，只能重启应用

### ISSUE THREAD

**Issue by vbinwang** [ilime/Petal#52]
![屏幕快照 2019-09-17 下午3 19 37](https://user-images.githubusercontent.com/53032400/65016183-974bef00-d95e-11e9-861d-a97b33e5b90a.png)
如图 点击dock里的图标不会出现应用界面，右击选择显示所有窗口提示没有窗口
系统是osx  10.14.6
此问题一下午会频繁出现好几次，希望大大们帮忙看一下，谢谢了

**Comment by g1eny0ung** [comment]
感谢反馈。

这个可能需要我们实际复现➕debug 一下，具体原因直接看应该是看不出来的。

另外新版本已经释出了，可以用一下新的版本看看还有没有这个问题。

[Release 2.20.0](https://github.com/ilime/Petal/releases/tag/v2.20.0)

**Comment by vbinwang** [comment]
好的 谢谢了 （补充，窗口消失之后音乐仍正常播放，dock点击图标后仍可以正常使用快捷键

**Comment by vbinwang** [comment]
试了2.20版本，辛苦了
但是问题依旧
更加具体的，只要是手动点击左上角的图标进行最小化，主界面便会消失，点击dock里的图标无法恢复正常窗口
谢谢了

**Comment by g1eny0ung** [comment]
@vbinwang 我也复现出来了，待排查一下。

**Comment by vbinwang** [comment]
好的，谢谢
----------------
补充：
不是点击左上角的最小化图标"-"，而是点击左上角的关闭'x'

**Comment by g1eny0ung** [comment]
@vbinwang 在 commit https://github.com/ilime/Petal/commit/6afef4a03bceeb6d82cbe5ed6f9b8066a5029230 中应该修复好这个问题了。

等下一个补丁版本释出就没问题了~

**Comment by vbinwang** [comment]
十分感谢！  辛苦了

Yue Yang <notifications@github.com>于2019年9月18日 周三下午5:53写道：
