### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by sunowsir** [ilime/Petal#56]
操作系统：deepin 15.11
petal版本: 2.20.0
问题：点击无反应，没有任何反应。

**Comment by g1eny0ung** [comment]
OK, 我们回头排查一下，electron 在 linux 上的打包确实有点问题。这次的 release 用的还是上一个版本的 electron 去打包的，最新的版本打出的deb包我在虚拟机上测试也是不能用。

**Comment by g1eny0ung** [comment]
@sunowsir deb 包更新了，可以试一下。

**Comment by sunowsir** [comment]
好的，谢谢 王新阳 邮箱：sunow.wang@gmail.com 签名由 网易邮箱大师 定制 在2019年09月23日 18:28，Yue Yang 写道： @sunowsir deb 包更新了，可以试一下。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ron159** [comment]
> @sunowsir deb 包更新了，可以试一下。

咦，请问在release哪里更新了吗，我上午下载安装还是一样的没有反应

**Comment by g1eny0ung** [comment]
@ron159 emmm，那应该就是 electron本身或者是打包命令不对的问题了，你也是deepin吗？

**Comment by ron159** [comment]
> @ron159 emmm，那应该就是 electron本身或者是打包命令不对的问题了，你也是deepin吗？

是的哦。那没关系，我先用着2.19吧。

**Comment by g1eny0ung** [comment]
@ron159 好的，因为目前没有多余的linux的机器，现在的deb包我在ubuntu虚拟机上测试是可以打开的，只是虚拟机的图形界面好像有些问题，所以显示是这样的：

![image](https://user-images.githubusercontent.com/15034155/65487036-9411af80-ded8-11e9-8bb9-76e3bc0e9b44.png)

我请 @Rapiz1 帮我测了一下，最新的 ubuntu 上面应该是没问题的，我们回头装个 deepin 试一下哈。

**Comment by ron159** [comment]
> @ron159 好的，因为目前没有多余的linux的机器，现在的deb包我在ubuntu虚拟机上测试是可以打开的，只是虚拟机的图形界面好像有些问题，所以显示是这样的：
> 
> ![image](https://user-images.githubusercontent.com/15034155/65487036-9411af80-ded8-11e9-8bb9-76e3bc0e9b44.png)
> 
> 我请 @Rapiz1 帮我测了一下，最新的 ubuntu 上面应该是没问题的，我们回头装个 deepin 试一下哈。

噢噢，那就太感谢了，辛苦了，谢谢。

**Comment by Rapiz1** [comment]
https://github.com/Rapiz1/Petal/releases/tag/2.20.1
已修复。在下一个 release 更新之前可以使用这个 pre-release。

**Comment by ron159** [comment]
> https://github.com/Rapiz1/Petal/releases/tag/2.20.1
> 已修复。在下一个 release 更新之前可以使用这个 pre-release。

正常使用了，感谢

**Comment by g1eny0ung** [comment]
@sunowsir @ron159 @Rapiz1 没有问题我就关闭 issue 了哈，今天或明天会 release 下一版。
