### ISSUE TITLE
每日私享歌单里的播放按钮失效（按下去没反应）

### ISSUE THREAD

**Issue by 2021Ready** [ilime/Petal#58]
每日私享歌单里的播放按钮失效（按下去没反应）
v2.21.0  and v2.20.0 都有这个问题

Windows 10 

Happy using Petal :hibiscus: ~.

If you want to open an issue:

Please make sure:

* [ ] Tell about your system info. (你的系统信息)
* [ ] The steps of your action. (你的操作步骤)
* [ ] In order to solve this issue better, It's best to have your error message or a screenshot. (为了更好的解决这个问题，最好能够提供一下你的错误信息或者是一张截图)

**Comment by g1eny0ung** [comment]
了解，知道是什么问题了，一会修复。

**Comment by g1eny0ung** [comment]
@2021Ready 新版本发布了，可以试一哈～

**Comment by g1eny0ung** [comment]
Since there is no response for a long time, close the issue.
