### ISSUE TITLE
一直在用Petal，可以改下窗口大小吗

### ISSUE THREAD

**Issue by mgss** [ilime/Petal#6]
用过好几个豆瓣FM客户端，就数这个最好用，但是美中不足的一点就是窗口太小可以改大点嘛?或者自定义窗口大小？
还有就是可以在任务栏图标点击后添加选择跳过、红心、垃圾桶的按钮吗？感谢作者~

**Comment by g1eny0ung** [comment]
感谢使用～。

关于窗口大小的问题，因为没什么额外的东西可以放置了，所以最开始设计的时候就固定窗口大小了。

你的系统是windows吗？windows我没用原生的菜单栏，貌似是显示不出来快捷键菜单。我回头会在图标出加上你说的按钮的。另外，虽然快捷键菜单显示不出来，但是快捷键是可以使用的。

快捷键列表：

- space => 暂停
- ctrl/command + L => 红心歌曲
- ctrl/command + K => 跳过当前播放列表
- ctrl/command + T => 将当前歌曲放入垃圾桶
- ctrl/command + Right => 向前一首歌曲（红心列表，最近播放列表）
- ctrl/command + Left => 向后一首歌曲（红心列表，最近播放列表）

**Comment by mgss** [comment]
好吧~
我是使用的macOS~还几有个小建议希望作者采纳：
- 可以考虑添加点关闭按钮之后自动隐藏在后台吗而不占用Dock栏的功能
- 可以考虑加个开机启动的设置，因为我配置了系统开机启动项后开机会自动播放音乐，有时候开外放会很尴尬

**Comment by g1eny0ung** [comment]
可以的，在下一个版本我会把这些做到设置功能里面。Good ideas.~

**Comment by g1eny0ung** [comment]
新版本已经释出。https://github.com/ilime/Petal/releases/tag/v2.8.0

**Comment by mgss** [comment]
好的~已经用上了~
那个功能可有可无~

**Comment by elliothe** [comment]
个人建议还是加入一下窗口大小调整或者让窗口的宽度可以调整。不然对于歌词部分很多时候只能看到一半，尤其是英文歌曲。

**Comment by g1eny0ung** [comment]
@elliothe 嗯嗯，会考虑加上的。横向的布局没有做自适应，但是纵向的可以加上。
