### ISSUE TITLE
你好，咨询关于下载的问题

### ISSUE THREAD

**Issue by GNINDLOEKIN** [ilime/Petal#60]
Happy using Petal :hibiscus: ~.

If you want to open an issue:

Please make sure:
我想知道点击下载歌曲我不知道他保存在什么位置了，麻烦告诉我一下，,然后再档案，所有下载里面没有下载的歌曲.2个问题，谢谢了.
* [ ] Tell about your system info. (win10 64x 1903)
* [ ] The steps of your action. (登录点击下载歌曲)
* [ ] In order to solve this issue better, It's best to have your error message or a screenshot. (为了更好的解决这个问题，最好能够提供一下你的错误信息或者是一张截图)

**Comment by g1eny0ung** [comment]
@GNINDLOEKIN Petal 设计时是只能够下载已经**红心**的歌曲，下载完毕后下载按钮旁边会显示一个小的绿色对勾✅，我上传了一张图片，你可以看一下：

![image](https://user-images.githubusercontent.com/15034155/66255664-fad87800-e7b8-11e9-921c-f851a2573296.png)

**Comment by GNINDLOEKIN** [comment]
好的，那么下载成功了，它存到什么地方了，我找不到。

在 2019年10月5日，21:42，Yue Yang <notifications@github.com> 写道：

@GNINDLOEKIN Petal 设计时是只能够下载已经红心的歌曲，下载完毕后下载按钮旁边会显示一个小的绿色对勾✅，我上传了一张图片，你可以看一下：

**Comment by g1eny0ung** [comment]
存放的目录是系统音乐目录下，不同系统的目录名可能不一样。

**Comment by g1eny0ung** [comment]
Since there is no response for a long time, close the issue.
