### ISSUE TITLE
无法关闭状态栏的歌词栏

### ISSUE THREAD

**Issue by zou2699** [ilime/Petal#62]
没有按钮可以关闭状态栏的歌词栏。像2.19那样，只有几个简单的按钮就行了。而且豆瓣的歌词也不全。

* [x] Tell about your system info. (你的系统信息) macOS 10.14.6
* [ ] The steps of your action. (你的操作步骤)
* [ ] In order to solve this issue better, It's best to have your error message or a screenshot. (为了更好的解决这个问题，最好能够提供一下你的错误信息或者是一张截图)

**Comment by g1eny0ung** [comment]
@zou2699 在 2.23.0 中完成 ✅。
