### ISSUE TITLE
状态栏垃圾桶按钮不起作用

### ISSUE THREAD

**Issue by yanganan** [ilime/Petal#68]
系统：Mac
系统版本：10.14.4
状态栏垃圾桶按钮不起作用，只能打开软件，点击放入垃圾桶
![image](https://user-images.githubusercontent.com/22971956/67733148-6ae4c180-fa38-11e9-94f5-544255e0595a.png)

**Comment by g1eny0ung** [comment]
回头看一下，这个状态栏在最新的 10.15 也有问题，图片显示有问题。。

最近有些忙，实在抱歉，后续一定修好！

**Comment by g1eny0ung** [comment]
@yanganan 在 2.23.0 中修复。

**Comment by g1eny0ung** [comment]
Since there is no response for a long time, close the issue.
