### ISSUE TITLE
arch编译的时候有些问题，不是很了解electron希望可以帮忙看看QAQ

### ISSUE THREAD

**Issue by icybest** [ilime/Petal#7]
我的环境是arch+gnome
node版本v10.0.0
nvm版本0.33.11
yarn版本1.6.0
在编译中间有个报错
[![2018-05-08 13-58-17屏幕截图.png](https://i.loli.net/2018/05/08/5af13cbe51168.png)](https://i.loli.net/2018/05/08/5af13cbe51168.png)
编译完之后运行编译出来的程序会提示
[![2018-05-08 13-57-13屏幕截图.png](https://i.loli.net/2018/05/08/5af13cbe4a8de.png)](https://i.loli.net/2018/05/08/5af13cbe4a8de.png)
不是太懂electron希望作者可以帮忙看看

**Comment by g1eny0ung** [comment]
你的编译步骤是什么呀，我还没有设置linux的打包📦，这个错误应该就是electron api在linux上会有一些限制导致的。

我今天试一下linux的打包，有进展之后回复你。

**Comment by g1eny0ung** [comment]
@icybest 我增加了 deb 的包还有 tar.gz 。

rpm 和 pacman的包我还没有打，因为在 ubuntu 上面用 deb 转 rpm 或者是 pacman 一堆错误。。还是要本平台打本平台的包最好，比如在 fedora 上面做 rpm 的打包。

如果你想使用 pacman，可以在 electron-builder.json 中，linux 那块：

```
"linux": {
    "category": "Audio",
    "icon": "./icons",
    "target": [
      "deb",
      "tar.gz"
    ]
}
```

target 里面加入 pacman 即可。然后运行`bash build.sh`

其他格式可以参考 [https://www.electron.build/configuration/linux](https://www.electron.build/configuration/linux)

**Comment by icybest** [comment]
已经编译成功了。感谢。软件很好用。

**Comment by g1eny0ung** [comment]
Thx~, 关闭issue了。
