### ISSUE TITLE
建议增加应用下载途径

### ISSUE THREAD

**Issue by xflhxz** [ilime/Petal#74]
github 上面的下载速度真的太慢了，平时下载项目的时候没这么慢过，就是单单下载这个客户端的时候这么慢，试了好几次还没下载成功

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by g1eny0ung** [comment]
好的，我一会儿加入一个百度云下载链接，确实没有 proxy 的话 GitHub 下载会很慢。

**Comment by g1eny0ung** [comment]
@xflhxz 已经添加了。
