### ISSUE TITLE
状态栏点跳过出现异常

### ISSUE THREAD

**Issue by tasselx** [ilime/Petal#8]
系统版本：Mac OS 10.13.4
操作步骤：1.启动Petal，最小化Petal 2.点击状态跳过就弹出如下图的异常
![image](https://user-images.githubusercontent.com/2656142/39822920-6e33c25c-53de-11e8-862d-5e2645e94965.png)

**Comment by g1eny0ung** [comment]
应该在 44b4db18e53cd7caefd5e49c63e7da4cbbc58ab5 修复了，新版本已释出。
