### ISSUE TITLE
build过程很顺利，但是运行时permission denied了

### ISSUE THREAD

**Issue by KKSun** [ilime/Petal#89]
macOS 10.15.4 
`yarn start:electron` ->

```
-------------------------------------
Node version:  12.13.0
Electron version:  8.0.0
Chrome version:  80.0.3987.86
-------------------------------------
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
db file existed.
install dev tools successfully
```
~~2020-07-06 01:17:50.613 Electron[16625:3978679] Persistent UI failed to open file file:///Users/sunhlf/Library/Saved%20Application%20State/com.github.Electron.savedState/window_4.data: Permission denied (13)~~

Permission 问题解决了，现在问题变成`yarn start:electron`之后的程序界面是纯白色的，能弹出Chrome调试工具，显示了warning，但是不显示程序界面？

**Comment by KKSun** [comment]
<img width="542" alt="Screen Shot 2020-07-06 at 12 25 30 PM" src="https://user-images.githubusercontent.com/15307921/86616419-cd0ca380-bf83-11ea-9be3-9f3d4df233ea.png">

感觉我的操作都没错，build了，dev运行的时候显示上面的图

**Comment by g1eny0ung** [comment]
感觉应该是你没有运行 `yarn start:electron` 的前置命令 `yarn build:electron:dev`。

**Comment by KKSun** [comment]
我傻了，没有yarn start🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️
