### ISSUE TITLE
是否能支持更多的源

### ISSUE THREAD

**Issue by pockry** [ilime/Petal#9]
支持一下作者，最近更新好频繁啊。

我之前是用豆瓣FM的，也很喜欢它的模式，现在是用QQ音乐，因为版权多，没办法。

不知道Petal能否支持更多的源，API接口能不能做成可配置的。

很喜欢Petal这个界面，希望能经常用~

**Comment by g1eny0ung** [comment]
emmm, 支持更多的源基本是不可能了。。因为这里面的所有逻辑都是围绕着豆瓣FM的API写的，隔离不出来了。

做这个的初衷就是豆瓣FM没有PC客户端，其他的音乐基本都有客户端，所以就分着用吧 :joy:。

**Comment by pockry** [comment]
好的，理解~

另一个问题就是昨天clone了项目下来想跑一下没跑起来，发现里面一个依赖模块 upath 只有1.04，只支持node 版本4到9之间，最好yarn upgrade一下。

**Comment by g1eny0ung** [comment]
有得package目前还没有升级依赖，所以upath会版本错误，yarn --ignore-engines 可以解决这个问题。

**Comment by g1eny0ung** [comment]
有的package目前还没有升级依赖，所以upath会报版本错误，yarn --ignore-engines 可以解决这个问题。
