### ISSUE TITLE
最新版进入后播放界面一直显示正在加载。。。

### ISSUE THREAD

**Issue by YangFanJack** [ilime/Petal#94]
Happy using Petal :hibiscus: ~.

If you want to open an issue:

Please make sure:

- [ ] Tell about your system info. (你的系统信息)
- [ ] The steps of your action. (你的操作步骤)
- [ ] In order to solve this issue better, It's best to have your error message or a screenshot. (为了更好的解决这个问题，最好能够提供一下你的错误信息或者是一张截图)

**Comment by g1eny0ung** [comment]
这个可能是两种问题，网络或者豆瓣的 API 自身问题，之前也会有这种情况。API 原因是因为豆瓣 API 返回的参数会缺失一些必要内容，导致请求被 pending。
